import React, { useState } from 'react';
import { BookOpen, ChevronDown, Clock, Search, Tag, X } from 'lucide-react';
import { Article } from '../../types';
import { ARTICLES_DATABASE } from '../../services/db';
import { EXTRA_ARTICLES } from '../../services/content/extraArticles';
import { toPersianDigits } from '../../services/jalali';

export const KnowledgeCenter: React.FC = () => {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('all');
  const [selected, setSelected] = useState<Article | null>(null);
  const [introOpen, setIntroOpen] = useState(false);
  const categories = [{ id: 'all', label: 'همه' }, { id: 'cat_routines', label: 'روتین' }, { id: 'cat_ingredients', label: 'ترکیبات' }, { id: 'cat_hormones', label: 'چرخه' }, { id: 'cat_sun_protection', label: 'ضدآفتاب' }, { id: 'cat_hair', label: 'مو' }];
  const articles = [...ARTICLES_DATABASE, ...EXTRA_ARTICLES].filter((article) => {
    const text = `${article.titleFa} ${article.summaryFa} ${article.tagsFa.join(' ')}`;
    return (category === 'all' || article.categoryId === category) && (!query.trim() || text.includes(query.trim()));
  });
  return <div className="pb-28 pt-3 px-4 max-w-lg mx-auto space-y-4">
    <div className="rounded-[1.7rem] bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 overflow-hidden shadow-sm">
      <button onClick={() => setIntroOpen((value) => !value)} className="w-full p-4 flex items-center justify-between text-right"><span className="flex items-center gap-2 text-sm font-black text-[#263b56] dark:text-white"><BookOpen className="w-5 h-5 text-rose-500" />پایگاه دانش آفلاین</span><ChevronDown className={`w-5 h-5 text-slate-400 transition-transform ${introOpen ? 'rotate-180' : ''}`} /></button>
      {introOpen && <div className="px-4 pb-4 space-y-1"><h2 className="text-lg font-black text-[#263b56] dark:text-white">یادگیری کوتاه، از پایه تا کاربرد</h2><p className="text-sm leading-7 text-slate-600 dark:text-slate-300">اول خلاصه ساده را بخوان. هر مقاله فقط یک نکته اصلی دارد و اگر خواستی، جزئیات بیشتر را باز کن.</p></div>}
    </div>
    <div className="space-y-3"><div className="relative"><Search className="absolute right-4 top-3.5 w-4 h-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جستجوی مقاله یا ترکیب" className="w-full rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 py-3 pr-11 pl-4 text-sm font-bold" /></div><div className="flex gap-2 overflow-x-auto no-scrollbar">{categories.map((item) => <button key={item.id} onClick={() => setCategory(item.id)} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-bold ${category === item.id ? 'bg-[#263b56] text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-500'}`}>{item.label}</button>)}</div></div>
    <div className="relative pr-7"><div className="absolute right-3 top-3 bottom-3 border-r-2 border-dashed border-rose-200 dark:border-rose-900" /><div className="space-y-4">{articles.map((article, index) => <div key={article.id} className="relative"><span className="absolute -right-[1px] top-5 z-10 w-7 h-7 rounded-full bg-rose-500 text-white text-xs font-black flex items-center justify-center ring-4 ring-[#faf8f5] dark:ring-slate-950">{toPersianDigits(index + 1)}</span><button onClick={() => setSelected(article)} className="w-full text-right rounded-[1.4rem] bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 p-4 pr-5 shadow-sm"><div className="flex items-center justify-between gap-2 text-xs text-slate-400"><span className="flex items-center gap-1 text-rose-600"><Tag className="w-3.5 h-3.5" />{article.categoryFa}</span><span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" />{toPersianDigits(article.readTimeMin)} دقیقه</span></div>{article.imageUrl && <img src={article.imageUrl} alt="" className="mt-3 w-full h-32 rounded-xl object-cover" loading="lazy" />}<h3 className="mt-3 text-base font-black text-[#263b56] dark:text-white leading-7">{article.titleFa}</h3><p className="mt-1 text-sm leading-7 text-slate-500 dark:text-slate-400 line-clamp-2">{article.summaryFa}</p><span className="block mt-3 text-xs font-bold text-rose-600">خواندن خلاصه و جزئیات</span></button></div>)}</div></div>
    {selected && <div className="fixed inset-0 z-50 bg-[#20334d]/45 flex items-center justify-center p-4"><article className="w-full max-w-lg max-h-[88vh] overflow-y-auto rounded-[2rem] bg-[#fffdf9] dark:bg-slate-900 p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold text-rose-600">{selected.categoryFa}</span><h2 className="mt-1 text-xl font-black text-[#263b56] dark:text-white leading-8">{selected.titleFa}</h2></div><button onClick={() => setSelected(null)} className="icon-only p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500"><X className="w-5 h-5" /></button></div>{selected.imageUrl && <img src={selected.imageUrl} alt="" className="mt-4 w-full h-44 rounded-2xl object-cover" />}<p className="mt-4 rounded-2xl bg-rose-50 dark:bg-rose-950/30 p-4 text-sm font-bold leading-8 text-slate-700 dark:text-slate-200">{selected.summaryFa}</p><p className="mt-4 whitespace-pre-line text-sm leading-8 text-slate-600 dark:text-slate-300">{selected.fullContentFa}</p><button onClick={() => setSelected(null)} className="mt-5 w-full rounded-2xl bg-[#263b56] py-3 text-sm font-bold text-white">بستن</button></article></div>}
  </div>;
};
