import { Ingredient } from '../../types';

/**
 * دیتابیس ترکیبات.
 *
 * تغییر مهم نسبت به نسخه ۱: روابط با شناسه (id) نگهداری می‌شوند نه
 * متن آزاد. قبلاً تداخل‌سنج با includes() روی نام کار می‌کرد که هم
 * خطای کاذب می‌داد و هم تداخل‌های واقعی را رد می‌کرد. الان می‌توانیم
 * تداخل محصولات قفسه کاربر را هم حساب کنیم.
 */
export const INGREDIENTS_DATABASE: Ingredient[] = [
  {
    id: 'ing_niacinamide',
    imageUrl: '/assets/real/ingredients/ingredient-1.webp',
    name: 'Niacinamide (Vitamin B3)',
    nameFa: 'نیاسینامید (ویتامین B3)',
    category: 'active',
    benefitsFa: ['تنطیم ترشح چربی پوست', 'کاهش التهاب و قرمزی جوش', 'کم‌رنگ کردن لک‌های تیره', 'کاهش ظاهر منافذ'],
    suitableSkinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_zinc_pca', 'ing_ceramides', 'ing_salicylic_acid', 'ing_panthenol', 'ing_azelaic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa:
      'نیاسینامید یکی از ایمن‌ترین و محبوب‌ترین ترکیبات مراقبت از پوست است که سد دفاعی پوست را تقویت کرده و تولید سِبوم را متعادل می‌کند. برخلاف باور قدیمی، مطالعات تازه نشان داده مصرف همزمان با ویتامین C مشکلی ایجاد نمی‌کند.',
  },
  {
    id: 'ing_retinol',
    imageUrl: '/assets/real/ingredients/ingredient-2.webp',
    name: 'Retinol (Vitamin A)',
    nameFa: 'رتینول (ویتامین A)',
    category: 'active',
    benefitsFa: ['تحریک کلاژن‌سازی', 'کاهش خطوط ریز و چروک', 'درمان جوش‌های سرسیاه و زیرپوستی', 'یکدست‌سازی بافت پوست'],
    suitableSkinTypes: ['oily', 'combination', 'normal', 'dry'],
    avoidSkinTypes: ['sensitive'],
    usageTime: 'night',
    pregnancySafety: 'avoid',
    breastfeedingSafety: 'avoid',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_niacinamide', 'ing_ceramides', 'ing_panthenol'],
    avoidCombiningIds: ['ing_salicylic_acid', 'ing_vitamin_c'],
    conflictReasonFa: 'مصرف همزمان با لایه‌بردارهای اسیدی سد دفاعی را تخریب می‌کند. یکی را صبح و دیگری را شب یا در شب‌های متفاوت استفاده کنید.',
    sideEffectsFa: 'در ۲ تا ۴ هفته اول ممکن است پوسته‌ریزی خفیف، خشکی یا سوزش ایجاد کند.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    descriptionFa:
      'موثرترین ترکیب اثبات‌شده برای نوسازی سلولی. حتماً فقط شب‌ها استفاده شود و مصرف ضدآفتاب در روز بعد الزامی است. قبل از لیزر، پیلینگ و اپیلاسیون باید چند روز قطع شود.',
  },
  {
    id: 'ing_salicylic_acid',
    imageUrl: '/assets/real/ingredients/ingredient-3.webp',
    name: 'Salicylic Acid (BHA)',
    nameFa: 'سالیسیلیک اسید (BHA)',
    category: 'exfoliant',
    benefitsFa: ['حل کردن چربی داخل منافذ', 'درمان جوش‌های سرسیاه و سرسفید', 'ضدالتهاب و آنتی‌باکتریال'],
    suitableSkinTypes: ['oily', 'combination'],
    avoidSkinTypes: ['dry', 'sensitive'],
    usageTime: 'both',
    pregnancySafety: 'consult_doctor',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_zinc_pca', 'ing_panthenol'],
    avoidCombiningIds: ['ing_retinol', 'ing_glycolic_acid'],
    conflictReasonFa: 'دو لایه‌بردار قوی در یک روتین باعث تخریب سد دفاعی و قرمزی ماندگار می‌شود.',
    irritationRisk: 'moderate',
    pauseBeforeProcedures: true,
    descriptionFa: 'یک لایه‌بردار محلول در چربی که به عمق منافذ نفوذ کرده و انسدادهای چربی و سلول‌های مرده را حل می‌کند.',
  },
  {
    id: 'ing_glycolic_acid',
    imageUrl: '/assets/real/ingredients/ingredient-4.webp',
    name: 'Glycolic Acid (AHA)',
    nameFa: 'گلیکولیک اسید (AHA)',
    category: 'exfoliant',
    benefitsFa: ['روشن‌سازی و شفافیت', 'یکدست کردن بافت و رنگ پوست', 'کمک به محو لک سطحی'],
    suitableSkinTypes: ['normal', 'combination', 'oily'],
    avoidSkinTypes: ['sensitive', 'dehydrated'],
    usageTime: 'night',
    pregnancySafety: 'consult_doctor',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: ['ing_retinol', 'ing_salicylic_acid', 'ing_vitamin_c'],
    conflictReasonFa: 'مصرف همزمان چند اسید یا اسید با رتینول، ریسک سوزش و لک التهابی را بالا می‌برد.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    descriptionFa: 'لایه‌بردار محلول در آب که سطح پوست را صیقل می‌دهد. حتماً شب و با ضدآفتاب روز بعد.',
  },
  {
    id: 'ing_hyaluronic_acid',
    imageUrl: '/assets/real/ingredients/ingredient-1.webp',
    name: 'Hyaluronic Acid',
    nameFa: 'هیالورونیک اسید',
    category: 'hydrator',
    benefitsFa: ['جذب و حفظ رطوبت', 'پرکردن خطوط ناشی از کم‌آبی', 'شاداب‌کننده فوری'],
    suitableSkinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_retinol', 'ing_vitamin_c', 'ing_salicylic_acid', 'ing_ceramides', 'ing_panthenol', 'ing_azelaic_acid', 'ing_centella', 'ing_glycolic_acid', 'ing_zinc_pca'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa: 'آب‌رسان قوی که رطوبت را به پوست می‌کشد. روی پوست نم‌دار بزنید و بلافاصله مرطوب‌کننده رویش بگذارید؛ در هوای خشک به تنهایی می‌تواند پوست را خشک‌تر کند.',
  },
  {
    id: 'ing_vitamin_c',
    imageUrl: '/assets/real/ingredients/ingredient-2.webp',
    name: 'Vitamin C (L-Ascorbic Acid)',
    nameFa: 'ویتامین C (آنتی‌اکسیدان)',
    category: 'antioxidant',
    benefitsFa: ['خنثی‌سازی رادیکال‌های آزاد', 'روشن‌کننده و شفاف‌کننده', 'کمک به ساخت کلاژن', 'تقویت اثر ضدآفتاب'],
    suitableSkinTypes: ['dry', 'normal', 'combination', 'oily'],
    avoidSkinTypes: ['sensitive'],
    usageTime: 'morning',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_niacinamide', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: ['ing_retinol', 'ing_glycolic_acid'],
    conflictReasonFa: 'با رتینول و اسیدهای قوی در یک نوبت مصرف نشود. ویتامین C مخصوص روتین صبح است.',
    irritationRisk: 'moderate',
    descriptionFa: 'سپر دفاعی روزانه پوست در برابر آلودگی و آفتاب. برای هوای آلوده شهرهای بزرگ کاملاً توصیه می‌شود.',
  },
  {
    id: 'ing_ceramides',
    imageUrl: '/assets/real/ingredients/ingredient-3.webp',
    name: 'Ceramides',
    nameFa: 'سرامیدها (ترمیم‌کننده سد دفاعی)',
    category: 'barrier_repair',
    benefitsFa: ['ترمیم سد دفاعی آسیب‌دیده', 'جلوگیری از تبخیر رطوبت', 'کاهش سوزش و کشیدگی'],
    suitableSkinTypes: ['dry', 'sensitive', 'dehydrated', 'combination', 'normal', 'oily'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_retinol', 'ing_glycolic_acid', 'ing_salicylic_acid', 'ing_niacinamide', 'ing_hyaluronic_acid', 'ing_panthenol'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa: 'چسب طبیعی بین سلول‌های پوست. بعد از لیزر، پیلینگ و در روزهای قاعدگی بهترین انتخاب است.',
  },
  {
    id: 'ing_azelaic_acid',
    imageUrl: '/assets/real/ingredients/ingredient-4.webp',
    name: 'Azelaic Acid',
    nameFa: 'آزلائیک اسید',
    category: 'active',
    benefitsFa: ['کاهش قرمزی و رزاسه', 'کم‌رنگ کردن لک و ملاسما', 'ضدجوش ملایم'],
    suitableSkinTypes: ['sensitive', 'dry', 'oily', 'combination', 'normal'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_centella', 'ing_ceramides'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa:
      'گزینه طلایی برای پوست حساس، رزاسه و لک. تنها ترکیب موثر ضدلک که در بارداری هم معمولاً مجاز است؛ با این حال با پزشک خود مشورت کنید.',
  },
  {
    id: 'ing_centella',
    imageUrl: '/assets/real/ingredients/ingredient-1.webp',
    name: 'Centella Asiatica (Cica)',
    nameFa: 'سنتلا آسیاتیکا (سیکا)',
    category: 'soother',
    benefitsFa: ['التیام‌بخش سریع', 'کاهش التهاب و سوزش', 'بازسازی بافت آسیب‌دیده'],
    suitableSkinTypes: ['sensitive', 'dry', 'oily', 'combination', 'normal', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_azelaic_acid', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa: 'ترکیب تسکین‌دهنده محبوب کره‌ای، مناسب برای روزهای پس از خدمات زیبایی و دوره قاعدگی.',
  },
  {
    id: 'ing_zinc_pca',
    imageUrl: '/assets/real/ingredients/ingredient-2.webp',
    name: 'Zinc PCA',
    nameFa: 'زینک پی‌سی‌ای',
    category: 'active',
    benefitsFa: ['مات‌کننده چربی اضافی', 'ضدمیکروب عامل آکنه', 'کاهش ظاهر منافذ باز'],
    suitableSkinTypes: ['oily', 'combination'],
    avoidSkinTypes: ['dry'],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_salicylic_acid', 'ing_hyaluronic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa: 'ترکیب زینک و عامل مرطوب‌کننده طبیعی پوست که چربی بی‌رویه را کنترل می‌کند.',
  },
  {
    id: 'ing_panthenol',
    imageUrl: '/assets/real/ingredients/ingredient-3.webp',
    name: 'Panthenol (Pro-Vitamin B5)',
    nameFa: 'پانتنول (پرو ویتامین B5)',
    category: 'soother',
    benefitsFa: ['آب‌رسانی عمیق', 'تسکین خارش و سوزش', 'افزایش انعطاف‌پذیری پوست'],
    suitableSkinTypes: ['dry', 'sensitive', 'dehydrated', 'normal', 'combination', 'oily'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_ceramides', 'ing_centella', 'ing_retinol', 'ing_salicylic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    descriptionFa: 'پانتنول پس از جذب به ویتامین B5 تبدیل می‌شود و مانند مرهمی نرم، خشکی و التهاب را تسکین می‌دهد.',
  },
];

export function findIngredientById(id: string): Ingredient | undefined {
  return INGREDIENTS_DATABASE.find((item) => item.id === id);
}

export function findIngredientByName(query: string): Ingredient | undefined {
  const needle = query.trim().toLowerCase();
  if (!needle) return undefined;
  return INGREDIENTS_DATABASE.find(
    (item) => item.id === needle || item.name.toLowerCase() === needle || item.nameFa === query.trim(),
  );
}
