import React from 'react';
import { CloudOff, CloudSun, Droplets, Loader2, MapPin, Sun, Wind } from 'lucide-react';
import { WeatherData } from '../../types';
import { toPersianDigits } from '../../services/jalali';

interface Props { weather: WeatherData; onRequestLocation?: () => void; locationLoading?: boolean; locationError?: boolean; }
export const WeatherClimateCard: React.FC<Props> = ({ weather, onRequestLocation, locationLoading, locationError }) => {
  if (!weather.hasData) return <div className="p-4 rounded-3xl bg-white dark:bg-slate-900 border border-dashed border-slate-200 dark:border-slate-700 space-y-3"><div className="flex items-center gap-3"><CloudOff className="w-5 h-5 text-slate-400" /><div><h3 className="text-sm font-black text-slate-700 dark:text-slate-200">آب‌وهوای امروز</h3><p className="text-xs text-slate-500 mt-1">برای پیشنهاد دقیق‌تر پوست، موقعیتت را یک‌بار فعال کن.</p></div></div>{onRequestLocation && <button onClick={onRequestLocation} disabled={locationLoading} className="w-full py-3 rounded-2xl bg-[#eef3fa] dark:bg-slate-800 text-[#263b56] dark:text-white text-sm font-bold flex items-center justify-center gap-2">{locationLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <MapPin className="w-4 h-4" />}{locationLoading ? 'در حال دریافت موقعیت...' : 'فعال‌کردن موقعیت دقیق'} </button>}{locationError && <p className="text-xs text-rose-600 font-bold">اجازه موقعیت داده نشد؛ می‌توانی شهر را در پروفایل وارد کنی.</p>}</div>;
  const highUv = weather.uvIndex >= 6;
  return <div className="p-4 rounded-3xl bg-white dark:bg-slate-900 border border-rose-100 dark:border-slate-800 space-y-3"><div className="flex items-center gap-3"><CloudSun className="w-5 h-5 text-amber-500" /><div><h3 className="text-sm font-black text-slate-800 dark:text-white">{weather.city} · {toPersianDigits(weather.temp)} درجه</h3><p className="text-xs text-slate-500">{weather.conditionFa}{weather.isStale ? ' · داده قدیمی' : ''}</p></div></div><div className="grid grid-cols-2 gap-2"><div className={`p-3 rounded-2xl border ${highUv ? 'bg-rose-50 border-rose-200' : 'bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700'}`}><Sun className="w-4 h-4 inline ml-1" /><span className="text-xs font-bold">فرابنفش </span><strong className="text-sm">{toPersianDigits(weather.uvIndex)}</strong></div><div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><Droplets className="w-4 h-4 inline ml-1" /><span className="text-xs font-bold">رطوبت </span><strong className="text-sm">{toPersianDigits(weather.humidity)}٪</strong></div></div>{weather.recommendationFa && <p className="text-sm text-slate-600 dark:text-slate-300 leading-7"><Wind className="w-4 h-4 inline ml-1 text-rose-500" />{weather.recommendationFa}</p>}</div>;
};
